windranger-io/windranger-solidity-template

.prettierrc, hardhat.config.ts, scripts/sample-script.ts, test/bitdao.test.ts, tsconfig.json
Prettier standard, and Google template use a tab indent of four not two, changing it over.
=> chore: alphabetical ordering, standard indent.

package.json, test/bitdao.test.ts
=> chore: removing redundant async

.github/workflows/master-push-pull.yml
Requirement of the lint (TS & Sol) to pass as part of submitting PR.
=> feat: lint as part of PR

.github/ISSUE_TEMPLATE/question.md, README.md
A place to document our development processes. The idea being that we have agreed a shared approach to how we collaborate on creating our software.
How we can best discuss design changes or raise questions on existing or new code, while also keeping those discussions available for any interested party (internal of external to WindRanger) to easily view and participate.
My initial suggestion is to use GitHub Issues and Pull Requests. 
This PR contains another template for creating an Issue: Question (for beginning a conversation, perhaps about existing code in the repo, perhaps not).
Pull Requests remain as they are, purpose being to review changes before they are pulled into the repo.
If this approach doesn't work, then it can always be iterated on ...or changed wholesale 😉
=> docs: open communication

.github/workflows/master-push-pull.yml
=> ci: reverting to early version to test dependabot

README.md, package.json
=> feat: supporting UML rendering of puml files

package.json
=> revert: caret for typescript dependency

.github/dependabot.yml
Changing from daily to monthly cadence
=> ci: dependabot monthly updates

.github/dependabot.yml
=> ci: weekly check for actions update

.lintstagedrc
=> fix: format sol files on staging

hardhat.config.ts, test/box.test.ts, test/framework/events.ts
Code style updates to match the
=> fix: code style updates

package-lock.json, package.json
=> chore: typescript dependency updates

README.md
Documentation for how to run Slither locally or using Docker.
=> docs: slither

docs/development_process.md
=> docs: conventional comments not commit

README.md
=> fix: case correction to Windranger

package.json
Closes https://github.com/windranger-io/windranger-solidity-template/issues/108
Removing quotes has the commands working on both Window and MacOs, unsure about Linux native.
=> fix: removing single quotes for windows

.solhintignore
=> fix: updating solhint ignore

test/box-upgradability.test.ts, test/box.test.ts, test/contracts/box-events.ts, test/contracts/upgradable/upgradable-events.ts, test/contracts/verify-box-events.ts, test/tub.test.ts
=> fix: switching anonymous with types

hardhat.config.ts
Contract sizes are limited https://eips.ethereum.org/EIPS/eip-170
=> fix: limited contract sizes

.github/dependabot.yml
=> fix: dependabot replaced by renovate

package.json
=> fix: regex now searches multi-level directories

contracts/test/Tub.sol, test/framework/event-filters.ts, test/framework/event-wrapper.ts, test/framework/transaction.ts, test/tub.test.ts
Matching of ordered events, including partial matching
=> Ordered verify
